version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pricepulse_db
      POSTGRES_USER: pricepulse_user
      POSTGRES_PASSWORD: pricepulse_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://pricepulse_user:pricepulse_password@db:5432/pricepulse_db
      - REDIS_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A pricepulse worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://pricepulse_user:pricepulse_password@db:5432/pricepulse_db
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A pricepulse beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://pricepulse_user:pricepulse_password@db:5432/pricepulse_db
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data: